# Generated by Django 3.1.4 on 2020-12-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autthor',
            new_name='author',
        ),
    ]
